<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>DesktopKeychainApp</RootNamespace>
    <AssemblyName>DesktopKeychainApp</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="OneDrive\**" />
    <Compile Remove="accessory_prototype\**" />
    <Page Remove="OneDrive\**" />
    <Page Remove="accessory_prototype\**" />
    <ApplicationDefinition Remove="OneDrive\**" />
    <ApplicationDefinition Remove="accessory_prototype\**" />
    <None Remove="OneDrive\**" />
    <None Remove="accessory_prototype\**" />
    <EmbeddedResource Remove="OneDrive\**" />
    <EmbeddedResource Remove="accessory_prototype\**" />
    <Content Include="OneDrive\Documents\Allikk_Aabharanam-master\datasets\accessories\accessories.json"
             Link="datasets\accessories\accessories.json"
             CopyToOutputDirectory="PreserveNewest" />
    <Content Include="OneDrive\Documents\Allikk_Aabharanam-master\assets\*.jpg"
             Link="datasets\accessories\assets\%(Filename)%(Extension)"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
